# docker build -t tinybert-plain:0.0.1 -f Dockerfile.tinybert .
FROM mam10eks/reneuir-tinybert:0.0.1

ADD code/run-notebook.py /run-notebook.py
ADD code/re-rank-with-tiny-bert.ipynb /re-rank-with-tiny-bert.ipynb
RUN pip3 uninstall -y tira&& pip3 install runnb tira && jupyter trust /re-rank-with-tiny-bert.ipynb

ARG MODEL_NAME
RUN huggingface-cli download $MODEL_NAME
ENV MODEL=/model

ENTRYPOINT [ "/run-notebook.py", "--notebook", "/re-rank-with-tiny-bert.ipynb" ]

