FROM webis/ir-lab-wise-2023:0.0.4

ADD tiny-bert-ranker/run-notebook.py /run-notebook.py
ADD foo/append-retrieval.ipynb /append-retrieval.ipynb
RUN jupyter trust /append-retrieval.ipynb

ENTRYPOINT [ "/run-notebook.py", "--notebook", "/append-retrieval.ipynb" ]
