seed_everything: 42
trainer:
  devices: 1
    #precision: bf16
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      every_n_train_steps: null
  max_epochs: 3
  log_every_n_steps: 10
  accumulate_grad_batches: 1
  gradient_clip_val: 10
  gradient_clip_algorithm: null
data:
  class_path: lightning_ir.LightningIRDataModule
  init_args:
    num_workers: 0
    train_batch_size: 4
    shuffle_train: true
    inference_batch_size: 4
    train_dataset:
      class_path: lightning_ir.data.dataset.RunDataset
      init_args:
        # zcat ../../data/rank-distillm-run.gz > ../../data/rank-distillm.run
        run_path: ../../data/__colbert-10000-sampled-100__msmarco-passage-train-judged.run
        targets: rank
        depth: 100
        sample_size: 100
        sampling_strategy: top
model:
  class_path: lightning_ir.cross_encoder.mono.MonoBertModule
  init_args:
    model_name_or_path: prajjwal1/bert-tiny
    config:
      class_path: lightning_ir.MonoBertConfig
      init_args:
        query_length: 32
        doc_length: 256
    loss_functions:
    - class_path: lightning_ir.RankNet
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05
