name: Upload Docker Software to TIRA
on: 
  workflow_dispatch:
    inputs:
      dockerdir:
        description: The path to the Dockerfile that you want to build and execute.
        required: true
        default: tiny-bert-ranker/Dockerfile
      model:
        description: The huggingface model you want to embedd in the Docker image.
        required: true
        default: webis/tiny-bert-ranker
jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      -
        name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip install tira
      - name: Build, test, and upload image
        run: |
          cd ${{ github.workspace }}
          tira-cli login --token ${{ secrets.TIRA_AUTH_TOKEN }}
          docker build -t ${inputs.dockerdir} -f ${{ inputs.dockerdir }}/Dockerfile --build-arg MODEL_NAME=${{ inputs.model }} .
          tira-run --input-dataset reneuir-2024/re-rank-spot-check-20240624-training --image ${{ inputs.dockerdir }} --push true --fail-if-output-is-empty
